def commitMsg = params.commit_message
DEPLOY_ENV_DEV = "dev"
DEPLOY_ENV_PRE = "preprod"
DEPLOY_ENV_PROD = "prod"

pipeline {
    agent any

    environment {
        DEVOPS_PROJECT = 'DW_D'
        JAVA_HOME = '/usr/lib/jvm/zulu-11-amd64/'
        DOCKER_REPO = 'docker_repo_name'
        PROJECT_NAME='project'
        MS_NAME = 'ms-name'
        DOCKER_REPO_PASSWORD = credentials('docker_api_token')
        KUBEPROD_CREDS = credentials('kubeprod_config')
        KUBEPRE_CREDS = credentials('kubepreprod_config')
        KUBEDEV_CREDS = credentials('kubedevelop_config')
        KUBE_CREDS = ''
        JENKINS_API_CREDS=credentials('jenkins_api_creds')
    }
     
    stages {
        stage('Send to the Job'){
            steps {
                sh """
                   curl -s -k -X POST -L --user $JENKINS_API_CREDS "https://jenkins.domain.name/job/ProjectName/job/Test-Slack/buildWithParameters?buildUrl=$BUILD_URL"
                   """
            }
        }
    }
}
